import Head from "next/head";
import Navbar from "../../components/Navbar";
import SocialButton from "../../components/SocialButton";
import ProjectPreview from "../../components/ProjectPreview";
import LocalTime from "../../components/LocalTime";


export default function Home() {
  return (
    <>
      <Head>
        <title>Emir Erkinbekov | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
        
        <div className="h-[32rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('/_.jpeg')] bg-cover">
          <div>
            
            <h1 className="text-4xl font-semibold">Hey I am Emir, I am a Software Engineer, Front-End dev with few years of experience.</h1>
          </div>
          <p className="flex-1">
            I am an 18 years old software engineer trying to become better at programming. Currently studying Computer Science at university UIC.
            i got interested in business when i was 12 and started programming at 15.
            </p>
            <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
              <button className="bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto">Contact me</button>
              <div className=" flex items-center gap-4">
                <SocialButton bgColor="twitter" href="https://x.com/emiredope"> <img src="/twitter.svg" alt="Twitter" className="w-5 h-5"/> </SocialButton>
                <SocialButton bgColor="linkedin" href="https://www.linkedin.com/in/emir-erkinbekov-200707245/"> <img src="/linkedin.svg" alt="LinkedIn" className="w-5 h-5"/> </SocialButton>
                <SocialButton bgColor="instagram" href="https://www.instagram.com/bigg__daddy___/"> <img src="/instagram.svg" alt="Instagram" className="w-5 h-5"/> </SocialButton>
                <SocialButton bgColor="github" href="https://github.com/emiredope"> <img src="/github.svg" alt="Github" className="w-5 h-5"/> </SocialButton>
              </div>
              <LocalTime />
            </div>     
        </div>
        <div className="h-[32rem] rounded-3xl p-8 bg-[url('/clouds.jpeg')] bg-cover bg-center"/>
      </section>

      <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4 ">
        <ProjectPreview
          name="Project 1"
          description="Coming soon..."
          imageUrl="/project-1.png"
          bgColor="#685cdd"
          dark
        />
        <ProjectPreview
          name="Project 2"
          description="Coming soon..."
          imageUrl="/project-2.png"
          bgColor="#313442"
          dark
        />
        <ProjectPreview
          name="Project 3"
          description="Coming soon..."
          imageUrl="/project-1.png"
        />
        <ProjectPreview
          name="Project 4"
          description="Coming soon..."
          bgColor="#4e4e56"
          dark
        />
        <ProjectPreview
          name="Project 5"
          description="Coming soon..."
          imageUrl="/project-2.png"
          bgColor="#171717"
          dark
        />
        <ProjectPreview
          name="Project 6"
          description="Coming soon..."
          imageUrl="/project-3.png"
          bgColor="#e4e4e7"

        />
      </section>

    </>
  );
}
